services:
    api-blue:
      image: adrifok/todo-api:latest
      environment:
        - MONGO_URI=mongodb://mongo:27017/todos
        - VERSION=blue
      depends_on:
        - mongo
      restart: unless-stopped

    api-green:
      image: adrifok/todo-api:latest
      environment:
        - MONGO_URI=mongodb://mongo:27017/todos
        - VERSION=green
      depends_on:
        - mongo
      restart: unless-stopped

    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - api-blue
        - api-green
      restart: unless-stopped

    mongo:
      image: mongo:7
      volumes:
        - mongo_data:/data/db
      restart: unless-stopped

volumes:
      mongo_data: